### ISSUE TITLE
Fail to import

### ISSUE THREAD

**Issue by RuiFeiHe** [yoyololicon/pytorch-NMF#18]
from torchnmf.nmf import NMF
*** torch.jit.frontend.NotSupportedError: unsupported kind of augumented assignment: BitOr:
  File "/home......../lib/python3.7/site-packages/torchnmf/nmf.py", line 44
            break

        zero_coef |= mask
                  ~~ <--- HERE
        v.relu_()
        v += (k1 - v.sum()) / (N - zero_coef.count_nonzero())

**Comment by RuiFeiHe** [comment]
solved. |= -> = ... |

**Comment by yoyololicon** [comment]
@RuiFeiHe 
Update pytorch to latest version should solve the issue.
